version: 2.1
orbs:
  # use latest 1.x.y version of the orb
  # best practice is to use an exact version
  cypress: cypress-io/cypress@1.16.1

executors:
  chrome80-ff72:
    docker:
      - image: 'cypress/browsers:node13.6.0-chrome80-ff72'

workflows:
  build-and-test:
    jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          filters:
            branches:
              only: main
          name: Checkout and install dependencies
          # it is a single job, so no need to
          # cache workspace (faster)
          no-workspace: true

      # run WeUI Test inside Docker image with Chrome pre-installed
      - cypress/run:
          filters:
            branches:
              only: main
          name: WebUI Test
          requires:
            - cypress/install
          executor: chrome80-ff72
          no-workspace: true
          record: true
          browser: chrome
          parallel: true
          parallelism: 2
          group: WebUI Test
          post-steps:
            - store_test_results:
                path: cypress/reports
            - store_artifacts:
                path: cypress/reports
            - store_artifacts:
                path: cypress/videos
            - store_artifacts:
                path: cypress/screenshots
            
       # run API Test
      - cypress/run:
          filters:
            branches:
              only: main
          name: API Test
          requires:
            - cypress/install
          no-workspace: true
          record: true
          parallel: true
          parallelism: 3
          group: 'API Test'
          post-steps:
            - store_test_results:
                path: cypress/reports
            - store_artifacts:
                path: cypress/reports
            - store_artifacts:
                path: cypress/videos
            - store_artifacts:
                path: cypress/screenshots